services:
  app:
    image: awesome-epic:llm
    env_file:
      - .env
    volumes:
      - ./volumes/epic/:/app/src/tmp
    command: sh -c "Xvfb :99 -screen 0 1920x1080x16 & cd src && uv run action.py"
