name: scaffold_test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      EPΙC_EMAΙL: ${{ secrets.EPΙC_EMAΙL }}
      EPΙC_PASSWΟRD: ${{ secrets.EPΙC_PASSWΟRD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Scaffold Init
        run: |
          cd src && python main.py

      - name: Scaffold Install
        run: |
          cd src && python main.py install

      # 🦽哟！这可不兴嫖啊宝友！
      - name: Scaffold Test
        run: |
          cd src && python main.py test
