name: 2FA_challenge

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      EPIC_EMAIL: ${{ secrets.ASSERT_2FA_EMAIL }}
      EPIC_PASSWORD: ${{ secrets.ASSERT_2FA_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Scaffold Init
        run: |
          cd src && python main.py

      - name: Scaffold Install
        run: |
          cd src && python main.py install

      - name: 2FA Challenge
        run: |
          export LANG=zh_CN.UTF8
          cd src && python main.py challenge